### PR TITLE
Cleanup in org.matrix.androisdk.call

### PR DESCRIPTION
**Pull request by awesome-manuel**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request updates [CHANGES.rst](https://github.com/matrix-org/matrix-android-sdk/blob/develop/CHANGES.rst)
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off)

### CODE REVIEW

**Comment by awesome-manuel** [comment]
@bmarty this is in line with ecc314546c633fb22b24b93eb20c53456b2261cd to simplify the calls implementation.

**Comment by bmarty** [comment]
Thanks @awesome-manuel ,
We will check this. After a first sight it seems correct, but I need to do more test.
Benoit

**Comment by awesome-manuel** [comment]
@bmarty any update on this?

**Comment by bmarty** [comment]
Hi @awesome-manuel 
I'm looking at your PR. Does it fixes some issue or is it just cleanup?

**Comment by awesome-manuel** [comment]
> Hi @awesome-manuel
> I'm looking at your PR. Does it fixes some issue or is it just cleanup?

This PR is just a cleanup. The only fix or workaround that seems to improve the situation is to remove the call to `PeerConnectionFactory.dispose()`.

**Comment by bmarty** [comment]
Ok, thanks.
It seems that commit 98cb1872da5f0815d9fe0930674c3ae77aac3927 has not been pushed to the PR. Is it intended?

image

**Comment by awesome-manuel** [comment]
98cb187 is just a preview and not completed yet, so it should go in a separate PR when it's ready.

**Comment by bmarty** [comment]
Ok, thanks for quick answer :)

**Pull request merged**
