### PR TITLE
fix excessive whitespace on quoted messages

### PR DESCRIPTION
**Pull request by dkanada**
This is not an ideal solution since it will also remove newlines even if a user intended to end a message with whitespace. I just wanted to see what solution you think is best. This code is a lot more simple than whatever would have to be done to selectively remove the newlines following quoted lines.

### CODE REVIEW

**Comment by dkanada** [comment]
Here is an image of what the whitespace looks like.

quote

**Comment by dkanada** [comment]
I have no idea how to integrate this into the android client manually but if you explain how I will test it out on my phone for a picture.

**Comment by bmarty** [comment]
Thanks for the PR.

To test with the Android client, just open Riot in Android studio and run the script `compile_with_sdk_project.sh`

**Comment by dkanada** [comment]
That was easier than expected, here is a photo after the fix.

**Comment by dkanada** [comment]
Signed-off-by: Dillon Kanada <dkanada@protonmail.com>

**Comment by bmarty** [comment]
Hello @dkanada ,

I think it's ok, because Riot removes any trailing space while sending messages, (if you like it or not by the way)

Benoît

**Pull request merged**
