### PR TITLE
Feature/update okttp retrofit

### PR DESCRIPTION
**Pull request by vincentbrison**
Move from Retrofit 1 to Retrofit 2, and from OkHttp 2 to OkHttp 3.

### CODE REVIEW

**Comment by bmarty** [comment]
Hi Vincent,

I'm working on merging your PR into develop. Since it's nearly 1 year old, I've got work to do, expecting to be done soon :-)

Benoit

**Comment by bmarty** [comment]
Hi @vincentbrison ,

I will merge your PR to a branch in our repository to be able to integrate your work into the Android Matrix SDK.

Could you please sign-off it as per https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off

Merci
Benoît

**Comment by vincentbrison** [comment]
Signed-off-by: Your Name <vincent.brison@fabernovel.com>

**Comment by vincentbrison** [comment]
Hi,

Is this sign-off enough?

BR,
Vincent

**Pull request merged**
